services:
  client:
    image: node:20-alpine
    container_name: client-container
    environment:
      - VITE_SERVER_URL=http://localhost:8000
      - VITE_SERVER_PORT=8000
      - VITE_SERVER_HOST=http://localhost
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    stdin_open: true
    tty: true